### ISSUE TITLE
Project description before Team

### ISSUE THREAD

**Issue by kumarkrishna** [Swarm-IITKgp/Swarm-IITKgp.github.io#13]
Having the project description before team listing would be better probably.

**Comment by abhinavjain241** [comment]
@kumarkrishna : I have switched the positions for the 'Team' and 'Project Description' section, you can see the live preview [here](http://abhinavjain241.github.io/Swarm-IITKgp.github.io). Also, I have switched the position for 'Contact Us' and 'Join Us'. 'Contact Us' is now before 'Join Us'. The reason for doing the same was that the colours for sections 'Join' and 'Team' were same.

If you find the change satisfactory, merge PR [#23](https://github.com/Swarm-IITKgp/Swarm-IITKgp.github.io/pull/23).

**Comment by abhinavjain241** [comment]
@kumarkrishna : Did you have a look into this?
